scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: actuator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8080"]
